apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-pipeline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-pipeline
  template:
    metadata:
      labels:
        app: devops-pipeline
    spec:
      containers:
        - name: devops-pipeline
          image: manishthakur2/devops-pipeline:latest
          ports:
            - containerPort: 5000
